/* automatically generated by rust-bindgen */

pub type __darwin_size_t = ::std::os::raw::c_ulong;
extern "C" {
    pub fn kd_quick(cd_key: *const ::std::os::raw::c_char, client_token: u32,
                    server_token: u32, public_value: *mut u32,
                    product: *mut u32,
                    hash_buffer: *mut ::std::os::raw::c_char,
                    buffer_len: usize) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn kd_init() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn kd_create(cdkey: *const ::std::os::raw::c_char,
                     keyLength: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn kd_free(decoder: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn kd_val2Length(decoder: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn kd_product(decoder: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn kd_val1(decoder: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn kd_val2(decoder: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn kd_longVal2(decoder: ::std::os::raw::c_int,
                       out: *mut ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn kd_calculateHash(decoder: ::std::os::raw::c_int, clientToken: u32,
                            serverToken: u32) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn kd_getHash(decoder: ::std::os::raw::c_int,
                      out: *mut ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn kd_isValid(decoder: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
}
